pipeline {
    agent { any { image 'maven:3.8.4-openjdk-11-slim' } }
    stages {
        stage('build') {
            steps {
                dir('vertx-kotlin-test') {
                    sh './mvnw package'
                }
            }
        }
        stage('test') {
            steps {
                 dir('vertx-kotlin-test') {
                     sh './mvnw clean test'
                  }
            }
        }
    }
    post {
        always {
            echo 'One way or another, I have finished'
            /* deleteDir() /*  clean up our workspace */
         }
        success {
            echo 'I succeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}
