name: Github Actions Emoji Casino
on:
  push:
    paths: aws/emoji-casino/backend/**
jobs:
  Emoji-Casino-Aws-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: cdk diff
        uses: actions/checkout@v2
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          uses: actions/checkout@v2
          actions_comment: true
          working_dir: 'aws/emoji-casino/backend'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-central-1'
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'aws/emoji-casino/backend'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'